apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: booking-project
  type: LoadBalancer