apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mariadb-service
      app: maria_db
  template:
    metadata:
      labels:
        component: mariadb-service
        app: maria_db
    spec:
      volumes:
        - name:  mariadb-database-persistent-volume-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc-claim
      containers:
        - name: mariadb
          image: "mariadb:10.4"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mdb-user
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mdb-user
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mdb-user
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: event_manager
          volumeMounts:
            - name: mariadb-database-persistent-volume-storage
              mountPath: /var/lib/mysql